from __future__ import annotations

from pathlib import Path

from .check import check_repo_result
from .graph_quality import graph_quality


def write_pr_comment(repo_path: Path, output: Path | None = None) -> Path:
    out = output or (repo_path / "keel-out" / "pr-comment.md")
    out.parent.mkdir(exist_ok=True)
    result = check_repo_result(repo_path)
    quality = graph_quality(repo_path)
    lines = [
        "## Keel Architecture Check",
        "",
        f"**Status:** {'failed' if result.blocking else 'passed'}",
        f"**Graph quality:** {quality['score']}/100 ({quality['status']})",
        f"**Blocking regressions:** {len(result.blocking)}",
        f"**Known baseline debt:** {len(result.known_debt)}",
        "",
    ]
    if result.blocking:
        lines.append("### Blocking Regressions")
        for violation in result.blocking:
            lines.append(f"- `{violation.contract_id}`: {violation.message}")
            if violation.repair_hint:
                lines.append(f"  Repair: {violation.repair_hint}")
        lines.append("")
    if quality.get("warnings"):
        lines.append("### Graph Quality Warnings")
        lines.extend(f"- {warning}" for warning in quality["warnings"])
        lines.append("")
    lines.append("Generated by Keel.")
    out.write_text("\n".join(lines), encoding="utf-8")
    return out

